// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDH_UKHOFuHjn2I3ENHGRdsoGlTdZ5FOp4',
    appId: '1:763847961456:web:56fb9f6ffc0336efe83db5',
    messagingSenderId: '763847961456',
    projectId: 'db-firebase-a2c97',
    authDomain: 'db-firebase-a2c97.firebaseapp.com',
    storageBucket: 'db-firebase-a2c97.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFbs1jdbNM1bCdNpd7lpxxDGctGzEsBNQ',
    appId: '1:763847961456:android:4b14de28173062d7e83db5',
    messagingSenderId: '763847961456',
    projectId: 'db-firebase-a2c97',
    storageBucket: 'db-firebase-a2c97.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjUOkb7oWQ_jexOkFshX9oLEJDPhBx7vQ',
    appId: '1:763847961456:ios:a0fd507c8ee283dde83db5',
    messagingSenderId: '763847961456',
    projectId: 'db-firebase-a2c97',
    storageBucket: 'db-firebase-a2c97.appspot.com',
    iosBundleId: 'com.stginnovacion.oneFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjUOkb7oWQ_jexOkFshX9oLEJDPhBx7vQ',
    appId: '1:763847961456:ios:344387ea37b67b7fe83db5',
    messagingSenderId: '763847961456',
    projectId: 'db-firebase-a2c97',
    storageBucket: 'db-firebase-a2c97.appspot.com',
    iosBundleId: 'com.stginnovacion.oneFlutter.RunnerTests',
  );
}
