// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKh1QaPF3m5pn51VOM9s1ufx0bGyQSm_M',
    appId: '1:352458789279:web:026f0ebbf7ef0037e8adaa',
    messagingSenderId: '352458789279',
    projectId: 'db-test-sis21',
    authDomain: 'db-test-sis21.firebaseapp.com',
    storageBucket: 'db-test-sis21.appspot.com',
    measurementId: 'G-4LY8WFGGFR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4_GWFBsK8wqHvPeU2NvTMf8cXPusLPN4',
    appId: '1:352458789279:android:6c10848c882ac19be8adaa',
    messagingSenderId: '352458789279',
    projectId: 'db-test-sis21',
    storageBucket: 'db-test-sis21.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZZ5XemxLa_AwZN4lpkl8y8wDzX7tbE3M',
    appId: '1:352458789279:ios:c071db77e7672ad9e8adaa',
    messagingSenderId: '352458789279',
    projectId: 'db-test-sis21',
    storageBucket: 'db-test-sis21.appspot.com',
    iosBundleId: 'com.stginnovacion.oneFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZZ5XemxLa_AwZN4lpkl8y8wDzX7tbE3M',
    appId: '1:352458789279:ios:4857ebb623fff872e8adaa',
    messagingSenderId: '352458789279',
    projectId: 'db-test-sis21',
    storageBucket: 'db-test-sis21.appspot.com',
    iosBundleId: 'com.stginnovacion.oneFlutter.RunnerTests',
  );
}
